const googleRules = require('eslint-config-google');

module.exports = [
  {
    files: ["gnome-ext/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        imports: "readonly",
        GLib: "readonly",
        Gio: "readonly",
        Main: "readonly",
        MessageTray: "readonly",
        St: "readonly",
        Clutter: "readonly",
        Meta: "readonly",
        Shell: "readonly",
        Atk: "readonly",
        Gdk: "readonly",
        Gtk: "readonly",
        Pango: "readonly",
        cairo: "readonly",
        console: "readonly",
      },
    },
    rules: {
      ...googleRules.rules,
      // Disable rules that conflict with Prettier (4-space indent)
      "indent": "off",
      "max-len": ["error", { code: 120, tabWidth: 4, ignoreUrls: true }],
      "arrow-parens": "off",
      "comma-dangle": "off",
      "brace-style": "off",
      "padded-blocks": "off",
      "keyword-spacing": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "block-spacing": "off",
      "object-curly-spacing": "off",
      "array-bracket-spacing": "off",
      "quotes": "off",
      "semi": "off",
      "no-multi-spaces": "off",
      "no-trailing-spaces": "off",
      "eol-last": "off",
      "linebreak-style": "off",
      // Disable rules that are overly strict or conflict with project style
      "require-jsdoc": "off",
      "valid-jsdoc": "off",
      "new-cap": "off",
      "one-var": "off",
      "no-multi-str": "off",
      // Allow empty catch blocks only with justification comment
      "no-empty": ["error", { allowEmptyCatch: true }],
      // Keep these Google rules that don't conflict with Prettier
      "no-var": "error",
      "prefer-const": ["error", { destructuring: "all" }],
      "no-unused-vars": ["error", { varsIgnorePattern: "^_", argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-redeclare": "error",
      "no-use-before-define": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-underscore-dangle": "off",
      "guard-for-in": "error",
      "no-caller": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-invalid-this": "error",
      "no-new-wrappers": "error",
      "no-throw-literal": "error",
      "no-with": "error",
      "prefer-promise-reject-errors": "error",
      "no-prototype-builtins": "error",
      "no-restricted-globals": "off",
      "no-restricted-syntax": "off",
      "no-magic-numbers": "off",
      "no-console": "off",
      "no-alert": "off",
      "no-debugger": "error",
      "no-unused-expressions": "error",
      "no-return-assign": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-unmodified-loop-condition": "error",
      "no-unused-labels": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "radix": "error",
      "require-await": "error",
      "yoda": "error",
      "block-scoped-var": "error",
      "default-case": "error",
      "dot-notation": "error",
      "eqeqeq": ["error", "always", { null: "ignore" }],
      "no-else-return": "error",
      "no-empty-function": "off",
      "no-empty-pattern": "error",
      "no-eq-null": "off",
      "no-eval": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "off",
      "no-implicit-globals": "off",
      "no-implied-eval": "error",
      "no-iterator": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-new-func": "error",
      "no-new": "off",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-proto": "error",
      "no-return-await": "error",
      "no-script-url": "error",
      "vars-on-top": "error",
      "wrap-iife": ["error", "any"],
      "prefer-arrow-callback": "error",
      "prefer-destructuring": "off",
      "prefer-numeric-literals": "error",
      "prefer-reflect": "off",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "arrow-body-style": "off",
      "arrow-spacing": "off",
      "constructor-super": "error",
      "generator-star-spacing": ["error", "after"],
      "no-class-assign": "error",
      "no-confusing-arrow": "off",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "off",
      "no-new-symbol": "error",
      "no-restricted-imports": "off",
      "no-this-before-super": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "object-shorthand": "error",
    },
  },
];