#!/usr/bin/env python3
"""IBus Cloud Speech engine launcher."""

import sys
import os
import logging

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

LOG_FILE = "/tmp/ibus-cloud.log"
logging.basicConfig(
    level=logging.DEBUG,
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ]
)

def log_exceptions(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return
    logger.error("Uncaught exception", exc_info=(exc_type, exc_value, exc_traceback))

sys.excepthook = log_exceptions

logger = logging.getLogger(__name__)
logger.info("=== Engine starting ===")

import gi
gi.require_version('IBus', '1.0')
from gi.repository import IBus, GLib

from ibus_cloud.engine import CloudSpeechEngine


class CloudSpeechFactory(IBus.Factory):
    __gtype_name__ = 'CloudSpeechFactory'

    def __init__(self, bus):
        self._bus = bus
        self._current_engine = None
        super().__init__(object_path=IBus.PATH_FACTORY,
                         connection=bus.get_connection())

    def do_create_engine(self, engine_name):
        logger.info("do_create_engine called: %s", engine_name)
        if engine_name != "com.cloud-voice.CloudSpeech":
            return super().do_create_engine(engine_name)

        engine = CloudSpeechEngine(self._bus, "/org/freedesktop/IBus/CloudSpeech/Engine")
        self._current_engine = engine
        logger.info("Created CloudSpeechEngine")
        return engine


def main():
    exec_by_ibus = "--ibus" in sys.argv
    logger.info("exec_by_ibus: %s", exec_by_ibus)
    
    IBus.init()
    logger.info("IBus.init() done")
    
    bus = IBus.Bus()
    logger.info("Bus created")
    
    loop = GLib.MainLoop()
    bus.connect("disconnected", lambda _: loop.quit())
    logger.info("Connected disconnected handler")
    
    factory = CloudSpeechFactory(bus)
    logger.info("Factory created")
    
    if exec_by_ibus:
        bus.request_name("com.cloud-voice.CloudSpeech", 0)
    else:
        component = IBus.Component.new(
            "com.cloud-voice.CloudSpeech",
            "Cloud Speech Input",
            "0.1.0",
            "MIT",
            "Voice-to-Text Contributors",
            "https://github.com/voice-to-text",
            "",
            "ibus-cloud",
        )
        engine_desc = IBus.EngineDesc.new(
            "com.cloud-voice.CloudSpeech",
            "Cloud Speech",
            "Cloud Speech Input Method",
            "en",
            "MIT",
            "Voice-to-Text Contributors",
            "audio-input-microphone",
            "default",
        )
        component.add_engine(engine_desc)
        bus.register_component(component)
    
    loop.run()


if __name__ == '__main__':
    main()